/**
 * Clarity Export Engine
 * Handles exporting documentation guides to HTML, Markdown, and PDF formats.
 * Also handles video download preparation.
 */

class ClarityExporter {
  constructor() {
    this.session = null;
  }

  setSession(session) {
    this.session = session;
  }

  // ── HTML Export ───────────────────────────────────────────────────────

  exportHTML() {
    if (!this.session || this.session.type !== 'guide') {
      throw new Error('No guide session loaded');
    }

    const steps = this.session.steps || [];
    const stepsHtml = steps
      .map(
        (step, i) => `
      <div class="step">
        <div class="step-header">
          <span class="step-number">${i + 1}</span>
          <h3 class="step-title">${escapeHtml(step.title || `Step ${i + 1}`)}</h3>
        </div>
        ${step.screenshot ? `<img class="step-screenshot" src="${step.screenshot}" alt="Step ${i + 1}" />` : ''}
        <p class="step-description">${escapeHtml(step.description || `Navigate to ${step.url} and ${step.title?.toLowerCase() || 'perform action'}`)}</p>
        <div class="step-meta">
          <span class="step-url">${escapeHtml(step.url || '')}</span>
          <span class="step-selector">${escapeHtml(step.selector || '')}</span>
        </div>
      </div>`
      )
      .join('\n');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(this.session.title)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Inter', sans-serif;
      background: #fff;
      color: #000;
      max-width: 720px;
      margin: 0 auto;
      padding: 40px 20px;
      -webkit-font-smoothing: antialiased;
    }
    h1 {
      font-size: 28px;
      font-weight: 700;
      letter-spacing: -0.5px;
      margin-bottom: 8px;
    }
    .meta {
      font-size: 13px;
      color: #888;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 1px solid #eee;
    }
    .step {
      margin-bottom: 32px;
      padding-bottom: 32px;
      border-bottom: 1px solid #f0f0f0;
    }
    .step:last-child { border-bottom: none; }
    .step-header {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 12px;
    }
    .step-number {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 28px;
      height: 28px;
      border-radius: 50%;
      background: #000;
      color: #fff;
      font-size: 13px;
      font-weight: 600;
      flex-shrink: 0;
    }
    .step-title {
      font-size: 16px;
      font-weight: 600;
    }
    .step-screenshot {
      width: 100%;
      border-radius: 8px;
      border: 1px solid #e5e5e5;
      margin-bottom: 12px;
    }
    .step-description {
      font-size: 14px;
      line-height: 1.6;
      color: #444;
      margin-bottom: 8px;
    }
    .step-meta {
      font-size: 11px;
      color: #aaa;
    }
    .step-url { margin-right: 12px; }
    .footer {
      text-align: center;
      font-size: 11px;
      color: #ccc;
      margin-top: 40px;
    }
  </style>
</head>
<body>
  <h1>${escapeHtml(this.session.title)}</h1>
  <div class="meta">${steps.length} steps &middot; Created with Clarity</div>
  ${stepsHtml}
  <div class="footer">Generated by Clarity</div>
</body>
</html>`;
  }

  // ── Markdown Export ───────────────────────────────────────────────────

  exportMarkdown() {
    if (!this.session || this.session.type !== 'guide') {
      throw new Error('No guide session loaded');
    }

    const steps = this.session.steps || [];
    let md = `# ${this.session.title}\n\n`;
    md += `*${steps.length} steps*\n\n---\n\n`;

    for (let i = 0; i < steps.length; i++) {
      const step = steps[i];
      md += `## Step ${i + 1}: ${step.title || 'Action'}\n\n`;
      if (step.description) {
        md += `${step.description}\n\n`;
      } else {
        md += `Navigate to \`${step.url || ''}\` and ${step.title?.toLowerCase() || 'perform action'}.\n\n`;
      }
      if (step.screenshot) {
        md += `![Step ${i + 1}](${step.screenshot})\n\n`;
      }
      md += `- **Element:** \`${step.selector || ''}\`\n`;
      md += `- **URL:** ${step.url || ''}\n\n`;
      if (i < steps.length - 1) md += `---\n\n`;
    }

    md += `\n---\n*Generated by Clarity*\n`;
    return md;
  }

  // ── PDF Export ────────────────────────────────────────────────────────

  exportPDF() {
    // Generate HTML and use the browser's print-to-PDF capability
    const html = this.exportHTML();
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => printWindow.print(), 500);
    }
  }

  // ── Video Download ────────────────────────────────────────────────────

  static downloadVideo(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename || `clarity-recording-${Date.now()}.webm`;
    a.style.display = 'none';
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      a.remove();
      URL.revokeObjectURL(url);
    }, 100);
  }

  // ── Blob Download Helper ──────────────────────────────────────────────

  static downloadBlob(content, filename, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.style.display = 'none';
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      a.remove();
      URL.revokeObjectURL(url);
    }, 100);
  }
}

function escapeHtml(str) {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

if (typeof window !== 'undefined') {
  window.ClarityExporter = ClarityExporter;
}
